name: packages

on:
  push:
    branches:
      - main
    tags:
      - "*"
    paths:
      - Dockerfile
      - setup.cfg
      - "**/*.py"
      - .github/workflows/packages.yml
    workflow_dispatch:


jobs:
  docker-build-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
    steps:
      - name: Downcase REPO
        id: downcase
        run: |
            repo_name=${{ github.repository }}
            echo "repo=${repo_name,,}" >> $GITHUB_OUTPUT
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get commit short sha
        id: get-short-sha
        run: |
          shortSha=$(git rev-parse --short ${{ github.sha }})
          echo "commit_short_sha=$shortSha" >> $GITHUB_OUTPUT

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.8.0
        with:
          images: ghcr.io/${{ steps.downcase.outputs.repo }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v6.18.0
        with:
          context: .
          file: Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ steps.downcase.outputs.repo }}:${{ steps.get-short-sha.outputs.commit_short_sha }}
            ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
